# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Richard\Desktop\disploader.ui'
#
# Created: Thu Apr 05 19:56:15 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_dwUI(object):
    def setupUi(self, dwUI):
        dwUI.setObjectName("dwUI")
        dwUI.resize(644, 177)
        self.gridLayout = QtWidgets.QGridLayout(dwUI)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(dwUI)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.RenderEngine = QtWidgets.QComboBox(dwUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RenderEngine.sizePolicy().hasHeightForWidth())
        self.RenderEngine.setSizePolicy(sizePolicy)
        self.RenderEngine.setObjectName("RenderEngine")
        self.RenderEngine.addItem("")
        self.RenderEngine.addItem("")
        self.RenderEngine.addItem("")
        self.horizontalLayout.addWidget(self.RenderEngine)
        self.keepShader = QtWidgets.QCheckBox(dwUI)
        self.keepShader.setObjectName("keepShader")
        self.horizontalLayout.addWidget(self.keepShader)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(dwUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.pickMesh = QtWidgets.QPushButton(dwUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickMesh.sizePolicy().hasHeightForWidth())
        self.pickMesh.setSizePolicy(sizePolicy)
        self.pickMesh.setObjectName("pickMesh")
        self.horizontalLayout_5.addWidget(self.pickMesh)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_4 = QtWidgets.QLabel(dwUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_13.addWidget(self.label_4)
        self.udim = QtWidgets.QCheckBox(dwUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.udim.sizePolicy().hasHeightForWidth())
        self.udim.setSizePolicy(sizePolicy)
        self.udim.setObjectName("udim")
        self.horizontalLayout_13.addWidget(self.udim)
        self.pickMap = QtWidgets.QPushButton(dwUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickMap.sizePolicy().hasHeightForWidth())
        self.pickMap.setSizePolicy(sizePolicy)
        self.pickMap.setObjectName("pickMap")
        self.horizontalLayout_13.addWidget(self.pickMap)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.setup = QtWidgets.QPushButton(dwUI)
        self.setup.setObjectName("setup")
        self.gridLayout.addWidget(self.setup, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(dwUI)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)

        self.retranslateUi(dwUI)
        QtCore.QMetaObject.connectSlotsByName(dwUI)

    def retranslateUi(self, dwUI):
        dwUI.setWindowTitle(QtWidgets.QApplication.translate("dwUI", "Displacement wizard", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("dwUI", "Render Engine..........................", None, -1))
        self.RenderEngine.setItemText(0, QtWidgets.QApplication.translate("dwUI", "Arnold", None, -1))
        self.RenderEngine.setItemText(1, QtWidgets.QApplication.translate("dwUI", "Renderman", None, -1))
        self.RenderEngine.setItemText(2, QtWidgets.QApplication.translate("dwUI", "Vray", None, -1))
        self.keepShader.setText(QtWidgets.QApplication.translate("dwUI", "keep current shader", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("dwUI", "Mesh...........................................", None, -1))
        self.pickMesh.setText(QtWidgets.QApplication.translate("dwUI", "pick", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("dwUI", "Map.........................", None, -1))
        self.udim.setText(QtWidgets.QApplication.translate("dwUI", "UDIM", None, -1))
        self.pickMap.setText(QtWidgets.QApplication.translate("dwUI", "pick", None, -1))
        self.setup.setText(QtWidgets.QApplication.translate("dwUI", "Setup Displacement", None, -1))

